### PR TITLE
github actions + opendronemap 2.0

### PR DESCRIPTION
**Pull request by robkooper**
This switches to use opendronemap 2.0
- this needs some significant testing

### CODE REVIEW

**Comment by max-zilla** [comment]
Got a failure to initialize:
```
8:54:02 mburnette@Minilla.local extractors-opendronemap github-actions docker run -it --rm --net=host -e REGISTRATION_ENDPOINTS="http://host.docker.internal:9000/api/extractors?key=xyz" -e RABBITMQ_URI="amqp://max:test@host.docker.internal:5672/%2f" -e CLOWDER_URL=http://host.docker.internal:9000 maxzilla2/opendronemap:latest bash    
[INFO]    Initializing ODM - Wed Nov 04 14:54:12  2020
[INFO]    ==============
[INFO]    build_overviews: False
[INFO]    camera_lens: auto
[INFO]    cameras: {}
[INFO]    crop: 3
[INFO]    debug: False
[INFO]    dem_decimation: 1
[INFO]    dem_euclidean_map: False
[INFO]    dem_gapfill_steps: 3
[INFO]    dem_resolution: 5
[INFO]    depthmap_resolution: 640
[INFO]    dsm: False
[INFO]    dtm: False
[INFO]    end_with: odm_report
[INFO]    fast_orthophoto: False
[INFO]    feature_quality: high
[INFO]    feature_type: sift
[INFO]    force_gps: False
[INFO]    gcp: None
[INFO]    geo: None
[INFO]    gps_accuracy: 15
[INFO]    ignore_gsd: False
[INFO]    matcher_distance: 0
[INFO]    matcher_neighbors: 8
[INFO]    max_concurrency: 8
[INFO]    merge: all
[INFO]    mesh_octree_depth: 10
[INFO]    mesh_point_weight: 4
[INFO]    mesh_samples: 1.0
[INFO]    mesh_size: 200000
[INFO]    min_num_features: 8000
[INFO]    mve_confidence: 0.6
[INFO]    name: bash
[INFO]    opensfm_depthmap_method: PATCH_MATCH
[INFO]    opensfm_depthmap_min_consistent_views: 3
[INFO]    opensfm_depthmap_min_patch_sd: 1
[INFO]    optimize_disk_space: False
[INFO]    orthophoto_compression: DEFLATE
[INFO]    orthophoto_cutline: False
[INFO]    orthophoto_no_tiled: False
[INFO]    orthophoto_png: False
[INFO]    orthophoto_resolution: 5
[INFO]    pc_classify: False
[INFO]    pc_csv: False
[INFO]    pc_ept: False
[INFO]    pc_filter: 2.5
[INFO]    pc_las: False
[INFO]    pc_rectify: False
[INFO]    pc_sample: 0
[INFO]    project_path: /
[INFO]    radiometric_calibration: none
[INFO]    rerun: None
[INFO]    rerun_all: False
[INFO]    rerun_from: None
[INFO]    resize_to: 2048
[INFO]    skip_3dmodel: False
[INFO]    sm_cluster: None
[INFO]    smrf_scalar: 1.25
[INFO]    smrf_slope: 0.15
[INFO]    smrf_threshold: 0.5
[INFO]    smrf_window: 18.0
[INFO]    split: 999999
[INFO]    split_multitracks: False
[INFO]    split_overlap: 150
[INFO]    texturing_data_term: gmi
[INFO]    texturing_keep_unseen_faces: False
[INFO]    texturing_nadir_weight: 16
[INFO]    texturing_outlier_removal_type: gauss_clamping
[INFO]    texturing_skip_global_seam_leveling: False
[INFO]    texturing_skip_hole_filling: False
[INFO]    texturing_skip_local_seam_leveling: False
[INFO]    texturing_skip_visibility_test: False
[INFO]    texturing_tone_mapping: none
[INFO]    tiles: False
[INFO]    time: False
[INFO]    use_3dmesh: False
[INFO]    use_exif: False
[INFO]    use_fixed_camera_params: False
[INFO]    use_hybrid_bundle_adjustment: False
[INFO]    use_opensfm_dense: False
[INFO]    verbose: False
[INFO]    ==============
[WARNING] Directory bash does not exist. Creating it now.
[INFO]    Running dataset stage
[INFO]    Loading dataset from: /bash/images
Traceback (most recent call last):
  File "/code/run.py", line 68, in <module>
    app.execute()
  File "/code/stages/odm_app.py", line 95, in execute
    self.first_stage.run()
  File "/code/opendm/types.py", line 337, in run
    self.process(self.args, outputs)
  File "/code/stages/dataset.py", line 93, in process
    files, rejects = get_images(images_dir)
  File "/code/stages/dataset.py", line 60, in get_images
    entries = os.listdir(in_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/bash/images'
```

**Comment by max-zilla** [comment]
...and without the -it attempt I was testing with:
```
docker run --rm --net=host -e REGISTRATION_ENDPOINTS="http://host.docker.internal:9000/api/extractors?key=xyz" -e RABBITMQ_URI="amqp://max:test@host.docker.internal:5672/%2f" -e CLOWDER_URL=http://host.docker.internal:9000 maxzilla2/opendronemap:latest  
usage: run.py [options] <project name>
run.py: error: argument <project name>: /bin/sh is not a valid name. Must use alphanumeric characters.
```

**Comment by robkooper** [comment]
@max-zilla updated the PR, did some testing as well.

**Review by bodom0015 — APPROVED** [review]
Did some very light/basic testing on some `brighton_beach` example dataset and others... looks good, no problems encountered :+1:

**Pull request merged**
